03 - Python - Django/myLearningDjangoProjects/01 - Restaurant/Restaurant/manager/urls.py
from django.urls import path
from .views import reservation_list, update_reservation, contact_list, update_contact, manager_page

app_name = "manager"

urlpatterns = [
    path("reservations/", reservation_list, name="reservations_list"),
    path("reservations/update/<int:pk>", update_reservation, name="update_reserve"),
    path("contact/", contact_list, name="contact_list"),
    path("contact/update/<int:pk>", update_contact, name="update_contact"),
    path('', manager_page, name="manager_page")
]

03 - Python - Django/myLearningDjangoProjects/01 - Restaurant/Restaurant/manager/templates/contact_list.html
{% extends 'account.html' %}

{% block content %}

    <!-- ======= Breadcrumbs Section ======= -->
    <section class="breadcrumbs">

        <div class="container">

            <div class="d-flex justify-content-between align-items-center">

                <h2>Контактна інформація</h2>

                <ol>
                    <li><a href="/">Головна</a></li>
                    <li><a href={% url 'manager:manager_page' %}>Менеджер</a></li>
                    <li>Контакти</li>
                </ol>

            </div>

        </div>

    </section>

    <section id="reserves">

        <div class="container">

            <div class="col-md-10 col-md-offset-1">
                {% for item in all_contacts %}

                    <div class="row">

                        <div class="col-md-3">
                            <a href="{% url 'manager:update_contact' pk=item.pk %}" class="btn btn-outline-danger" role="button" data-bs-toggle="button">Видалити заявку</a>
                        </div>

                        <div class="col-md-3">{{ item.name }}</div>
                        <div class="col-md-3">{{ item.email }}</div>
                        <div class="col-md-3">{{ item.subject }}</div>
                        <div class="col-md-3">{{ item.date_reservation }}</div>

                    </div>

                    <div class="row">
                        <div class="col-md-3"></div>
                        <div class="col-md-9"><p>{{ item.message }}</p></div>
                    </div>

                {% endfor %}

            </div>

        </div>

    </section>

{% endblock %}

03 - Python - Django/myLearningDjangoProjects/01 - Restaurant/Restaurant/manager/templates/manager_main_page.html
{% extends 'account.html' %}

{% block content %}

    <!-- ======= Breadcrumbs Section ======= -->
    <section class="breadcrumbs">

        <div class="container">

            <div class="d-flex justify-content-between align-items-center">

                <h2>Інтерфейс управління</h2>

                <ol>
                    <li><a href="/">Головна</a></li>
                    <li>Менеджер</li>
                </ol>

            </div>

        </div>

    </section>

    <section id="reserves">

        <div class="container">

            <div class="col-md-10 col-md-offset-1">

                <div class="section-title">
                    <div class="d-grid gap-2">
                        <a href="{% url 'manager:reservations_list' %}" class="btn btn-outline-success" role="button" data-bs-toggle="button">Бронювання</a>
                        <a href="{% url 'manager:contact_list' %}" class="btn btn-outline-info" role="button" data-bs-toggle="button">Контактні дані</a>
                    </div>
                </div>

            </div>

        </div>

    </section>

{% endblock %}

03 - Python - Django/myLearningDjangoProjects/01 - Restaurant/Restaurant/manager/templates/reservations_list.html
{% extends 'account.html' %}

{% block content %}

    <!-- ======= Breadcrumbs Section ======= -->
    <section class="breadcrumbs">

        <div class="container">

            <div class="d-flex justify-content-between align-items-center">

                <h2>Бронювання від гостей</h2>

                <ol>
                    <li><a href="/">Головна</a></li>
                    <li><a href={% url 'manager:manager_page' %}>Менеджер</a></li>
                    <li>Бронювання від гостей</li>
                </ol>

            </div>

        </div>

    </section>

    <section id="reserves">

        <div class="container">

            <div class="col-md-10 col-md-offset-1">

                {% for item in lst %}

                    <div class="row">

                        <div class="col-md-3">
                            <a href="{% url 'manager:update_reserve' pk=item.pk %}" class="btn btn-outline-primary" role="button" data-bs-toggle="button">Закрити заявку</a>
                        </div>

                        <div class="col-md-3">{{ item.name }}</div>
                        <div class="col-md-3">{{ item.phone }}</div>
                        <div class="col-md-3">{{ item.date_reservation }}</div>

                    </div>

                    <div class="row">
                        <div class="col-md-3"></div>
                        <div class="col-md-9"><p>{{ item.message }}</p></div>
                    </div>

                {% endfor %}

            </div>

        </div>

    </section>

{% endblock %}